From test_step02

ADD clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz /opt

#RUN wget https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz && tar xJf clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

